// src/views/CharInfo/CharInfoView.vue
<template>
<div class="root">
  <div class="col">{{$ls.chars}}: {{info.chars}}</div>
  <div class="col">{{$ls.charsNoSpaces}}: {{info.charsNoSpaces}}</div>
  <div class="col">{{$ls.lines}}: {{info.lines}}</div>
</div>
</template>

<script lang="ts">
import { Component, Vue, Prop } from 'vue-property-decorator';
import CharInfo from './CharInfo';

@Component
export default class CharInfoView extends Vue {
  @Prop() info!: CharInfo;
}
</script>

<style scoped>
.root {
  border-left: 4px solid navy;
  padding-left: 4px;
  display: flex;
  font-size: small;
  margin-bottom: 20px;
  margin-top: 10px;
}

.col {
  flex: 1 1 0;
}
</style>

// src/common/widgets/charInfoView.tsx
import * as React from 'react';
import app from 'common/app';
import { CharInfo } from '../util/charCounter';

export interface Props {
  charInfo: CharInfo;
}

export default class CharInfoView extends React.Component<Props, object> {
  constructor(props: Props) {
    super(props);
  }

  render() {
    const { props } = this;
    const ls = app.ls.charInfoView;
    const info = props.charInfo;
    return (
<div style={{borderLeft: '4px solid navy', paddingLeft: '4px', display: 'flex', fontSize: 'small', marginBottom: '20px', marginTop: '20px'}}>
  <div style={{flex: '1 1 0'}}>{ls.chars}: {info.chars}</div>
  <div style={{flex: '1 1 0'}}>{ls.charsNoSpaces}: {info.charsNoSpaces}</div>
  <div style={{flex: '1 1 0'}}>{ls.lines}: {info.lines}</div>
</div>
    );
  }
}
